apiVersion: v1
kind: Service
metadata:
  name: deviceregapi
  namespace: lbsite-tst
spec:
  type: ClusterIP
  selector:
    app: deviceregapi
  ports:
    - name: http
      port: 8081
      targetPort: 8081
