apiVersion: apps/v1
kind: Deployment
metadata:
  name: statisticsapi
  namespace: lbsite-tst
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statisticsapi
  template:
    metadata:
      labels:
        app: statisticsapi
    spec:
      containers:
        - name: statisticsapi
          image: DOCKER_HUB_USERNAME/statistics-api:latest # set your Docker Hub username
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: lbsite-db
                  key: url
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: lbsite-db
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lbsite-db
                  key: password
            - name: DEVICE_REGISTRATION_URL
              value: http://deviceregapi:8081
