server:
  port: 8082

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/lbsite}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

# URL of DeviceRegistrationAPI service
# In Kubernetes or Docker, override via env var DEVICE_REGISTRATION_URL
# Example: http://device-registration-api:8081
device:
  registration:
    url: ${DEVICE_REGISTRATION_URL:http://localhost:8081}

logging:
  level:
    org.hibernate.SQL: info
