apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lbsite-prd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ebalese/efintechb.git
    targetRevision: main
    path: infrastructure/helm/lbsite
    helm:
      valueFiles:
        - values/prd.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: lbsite-prd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
