name: Build DeviceRegistrationAPI

on:
  push:
    paths:
      - 'application/lbsite/DeviceRegistrationAPI/**'
      - '.github/workflows/build-device-registration.yml'
  pull_request:
    paths:
      - 'application/lbsite/DeviceRegistrationAPI/**'
      - '.github/workflows/build-device-registration.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: application/lbsite/DeviceRegistrationAPI

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B -DskipTests package

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: device-registration-api-jar
          path: application/lbsite/DeviceRegistrationAPI/target/*.jar
          if-no-files-found: error
