name: Promote to TST (Helm)

on:
  push:
    branches: [ "main" ]
    paths:
      - 'application/lbsite/**'
      - '.github/workflows/**'
      - 'infrastructure/helm/**'

permissions:
  contents: write
  pull-requests: write

jobs:
  update-values:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set image repo and tag in Helm values (tst)
        uses: mikefarah/yq@v4.43.1
        with:
          cmd: |
            yq -i '.statisticsapi.image.repository = "${{ secrets.DOCKER_HUB_USERNAME }}/statistics-api"' infrastructure/helm/lbsite/values/tst.yaml
            yq -i '.statisticsapi.image.tag = "${{ github.sha }}"' infrastructure/helm/lbsite/values/tst.yaml
            yq -i '.deviceregapi.image.repository = "${{ secrets.DOCKER_HUB_USERNAME }}/device-registration-api"' infrastructure/helm/lbsite/values/tst.yaml
            yq -i '.deviceregapi.image.tag = "${{ github.sha }}"' infrastructure/helm/lbsite/values/tst.yaml

      - name: Create Pull Request for TST values update
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "ci(helm): promote TST values to ${GITHUB_SHA}"
          title: "Promote TST to ${GITHUB_SHA}"
          body: |
            This PR updates TST Helm values to deploy images built from commit `${{ github.sha }}`.
            - statisticsapi: `${{ secrets.DOCKER_HUB_USERNAME }}/statistics-api:${{ github.sha }}`
            - deviceregapi: `${{ secrets.DOCKER_HUB_USERNAME }}/device-registration-api:${{ github.sha }}`
          branch: ci/promote-tst-${{ github.sha }}
          base: main
          add-paths: |
            infrastructure/helm/lbsite/values/tst.yaml
