name: Promote to PRD on Release (Helm + Docker)

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-and-push-images:
    name: Build and Push Images with Release Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build DeviceRegistrationAPI jar
        working-directory: application/lbsite/DeviceRegistrationAPI
        run: mvn -B -DskipTests package

      - name: Build StatisticsAPI jar
        working-directory: application/lbsite/StatisticsAPI
        run: mvn -B -DskipTests package

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push device-registration-api (release tag)
        uses: docker/build-push-action@v5
        with:
          context: application/lbsite/DeviceRegistrationAPI
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/device-registration-api:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push statistics-api (release tag)
        uses: docker/build-push-action@v5
        with:
          context: application/lbsite/StatisticsAPI
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/statistics-api:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  update-values:
    name: Update Helm values for PRD
    needs: build-and-push-images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update prd values with release tag
        uses: mikefarah/yq@v4.43.1
        with:
          cmd: |
            yq -i '.statisticsapi.image.repository = "${{ secrets.DOCKER_HUB_USERNAME }}/statistics-api"' infrastructure/helm/lbsite/values/prd.yaml
            yq -i '.statisticsapi.image.tag = "${{ github.ref_name }}"' infrastructure/helm/lbsite/values/prd.yaml
            yq -i '.deviceregapi.image.repository = "${{ secrets.DOCKER_HUB_USERNAME }}/device-registration-api"' infrastructure/helm/lbsite/values/prd.yaml
            yq -i '.deviceregapi.image.tag = "${{ github.ref_name }}"' infrastructure/helm/lbsite/values/prd.yaml

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add infrastructure/helm/lbsite/values/prd.yaml
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "ci(helm): promote PRD values to release ${{ github.ref_name }}"
            git push
          fi
