name: Promote to TST (Helm)

on:
  workflow_run:
    workflows: ["DeviceRegistrationAPI CI", "StatisticsAPI CI"]
    types: [completed]

permissions:
  contents: write
  pull-requests: write

jobs:
  update-values:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set image repo and tag in Helm values (tst)
        uses: mikefarah/yq@v4.43.1
        with:
          cmd: |
            yq -i '.statisticsapi.image.repository = "${{ secrets.DOCKER_HUB_USERNAME }}/statistics-api"' infrastructure/helm/lbsite/values/tst.yaml
            yq -i '.statisticsapi.image.tag = "${{ github.event.workflow_run.head_sha }}"' infrastructure/helm/lbsite/values/tst.yaml
            yq -i '.deviceregapi.image.repository = "${{ secrets.DOCKER_HUB_USERNAME }}/device-registration-api"' infrastructure/helm/lbsite/values/tst.yaml
            yq -i '.deviceregapi.image.tag = "${{ github.event.workflow_run.head_sha }}"' infrastructure/helm/lbsite/values/tst.yaml

      - name: Detect changes
        id: diff
        run: |
          git add infrastructure/helm/lbsite/values/tst.yaml
          if git diff --cached --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request for TST values update
        uses: peter-evans/create-pull-request@v6
        if: steps.diff.outputs.changed == 'true'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "ci(helm): promote TST values to sha:${{ github.event.workflow_run.head_sha }}"
          title: "Promote TST to sha:${{ github.event.workflow_run.head_sha }}"
          body: |
            This PR updates TST Helm values to deploy images built from CI commit:
            - statisticsapi: `${{ secrets.DOCKER_HUB_USERNAME }}/statistics-api:${{ github.event.workflow_run.head_sha }}`
            - deviceregapi: `${{ secrets.DOCKER_HUB_USERNAME }}/device-registration-api:${{ github.event.workflow_run.head_sha }}`
          branch: ci/promote-tst-${{ github.event.workflow_run.head_sha }}
          base: main
          add-paths: |
            infrastructure/helm/lbsite/values/tst.yaml
          labels: |
            ci
            promote-tst
