name: Promote to TST (Helm)

on:
  push:
    branches: [ "main" ]
    paths:
      - 'application/lbsite/**'
      - '.github/workflows/**'
      - 'infrastructure/helm/**'

permissions:
  contents: write

jobs:
  update-values:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set image repo and tag in Helm values (tst)
        uses: mikefarah/yq@v4.43.1
        with:
          cmd: |
            yq -i '.statisticsapi.image.repository = "${{ secrets.DOCKER_HUB_USERNAME }}/statistics-api"' infrastructure/helm/lbsite/values/tst.yaml
            yq -i '.statisticsapi.image.tag = "latest"' infrastructure/helm/lbsite/values/tst.yaml
            yq -i '.deviceregapi.image.repository = "${{ secrets.DOCKER_HUB_USERNAME }}/device-registration-api"' infrastructure/helm/lbsite/values/tst.yaml
            yq -i '.deviceregapi.image.tag = "latest"' infrastructure/helm/lbsite/values/tst.yaml

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add infrastructure/helm/lbsite/values/tst.yaml
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "ci(helm): promote TST values to latest"
            git push
          fi
