name: Promote to TST (Helm)

on:
  workflow_run:
    workflows: ["DeviceRegistrationAPI CI", "StatisticsAPI CI"]
    types: [completed]

permissions:
  contents: write
  pull-requests: write

jobs:
  update-values:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
      GITHUB_OWNER: ${{ github.repository_owner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker login
        if: ${{ env.DOCKER_HUB_USERNAME && env.DOCKER_HUB_TOKEN }}
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_TOKEN }}

      - name: Install yq
        run: |
          sudo curl -L "https://github.com/mikefarah/yq/releases/download/v4.43.1/yq_linux_amd64" -o /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq

      - name: Resolve image digests
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.DOCKER_HUB_USERNAME }}/statistics-api
            ${{ env.DOCKER_HUB_USERNAME }}/device-registration-api
          tags: |
            sha-${{ github.event.workflow_run.head_sha }}
            ${{ github.event.workflow_run.head_sha }}
            ${{ github.event.workflow_run.head_sha_short }}
          type: sha

      - name: Update Helm TST values
        run: |
          yq -i '.statisticsapi.image.repository = "'"${{ env.DOCKER_HUB_USERNAME }}/statistics-api"'" |
                 .statisticsapi.image.digest = "'"${{ steps.meta.outputs.statistics-api_digest }}"'" |
                 del(.statisticsapi.image.tag)' infrastructure/helm/lbsite/values/tst.yaml

          yq -i '.deviceregapi.image.repository = "'"${{ env.DOCKER_HUB_USERNAME }}/device-registration-api"'" |
                 .deviceregapi.image.digest = "'"${{ steps.meta.outputs.device-registration-api_digest }}"'" |
                 del(.deviceregapi.image.tag)' infrastructure/helm/lbsite/values/tst.yaml

      - name: Detect changes
        id: diff
        run: |
          git add infrastructure/helm/lbsite/values/tst.yaml
          if git diff --cached --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request for TST values update
        uses: peter-evans/create-pull-request@v6
        if: steps.diff.outputs.changed == 'true'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "ci(helm): promote TST values to digests for sha:${{ github.event.workflow_run.head_sha }}"
          title: "Promote TST to digests for sha:${{ github.event.workflow_run.head_sha }}"
          body: |
            This PR updates TST Helm values to deploy images (pinned by digest) built from CI commit `${{ github.event.workflow_run.head_sha }}` :
            - statisticsapi: `${{ env.DOCKER_HUB_USERNAME }}/statistics-api@sha256:${{ steps.meta.outputs.statistics-api_digest }}` \
            - deviceregapi: `${{ env.DOCKER_HUB_USERNAME }}/device-registration-api@sha256:${{ steps.meta.outputs.device-registration-api_digest }}` \
          branch: ci/promote-tst-${{ github.event.workflow_run.head_sha }}
          base: main
          add-paths: infrastructure/helm/lbsite/values/tst.yaml
          labels: ci,promote-tst
