name: Promote to TST (Helm)

on:
  workflow_run:
    workflows: ["DeviceRegistrationAPI CI", "StatisticsAPI CI"]
    types: [completed]

permissions:
  contents: write
  pull-requests: write

jobs:
  update-values:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker login (optional)
        if: ${{ secrets.DOCKER_HUB_USERNAME != '' && secrets.DOCKER_HUB_TOKEN != '' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Install yq
        shell: bash
        run: |
          sudo curl -L "https://github.com/mikefarah/yq/releases/download/v4.43.1/yq_linux_amd64" -o /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq

      - name: Resolve image digests and update Helm values (tst)
        id: update-values
        shell: bash
        env:
          # Prefer secret if present; otherwise default to the repo owner (works for public Docker Hub orgs matching GitHub user/org)
          DOCKER_ORG: ${{ secrets.DOCKER_HUB_USERNAME != '' && secrets.DOCKER_HUB_USERNAME || github.repository_owner }}
        run: |
          set -euo pipefail
          SHA="${{ github.event.workflow_run.head_sha }}"
          USER="${DOCKER_ORG}"

          # Resolve digests for images tagged with the commit SHA
          STAT_IMG="docker.io/${USER}/statistics-api:${SHA}"
          DEV_IMG="docker.io/${USER}/device-registration-api:${SHA}"

          # Try to resolve digests; if images aren't published yet for this SHA, exit with a clear message.
          set +e
          STAT_DIGEST_FULL=$(docker buildx imagetools inspect "${STAT_IMG}" --format '{{json .Manifest.Digest}}' 2>/dev/null | tr -d '"')
          STAT_RC=$?
          DEV_DIGEST_FULL=$(docker buildx imagetools inspect "${DEV_IMG}" --format '{{json .Manifest.Digest}}' 2>/dev/null | tr -d '"')
          DEV_RC=$?
          set -e

          if [ "$STAT_RC" -ne 0 ] || [ -z "$STAT_DIGEST_FULL" ]; then
            echo "::error::Could not resolve digest for ${STAT_IMG}. Ensure the CI pushed this image tag (commit SHA) to Docker Hub." >&2
            exit 1
          fi
          if [ "$DEV_RC" -ne 0 ] || [ -z "$DEV_DIGEST_FULL" ]; then
            echo "::error::Could not resolve digest for ${DEV_IMG}. Ensure the CI pushed this image tag (commit SHA) to Docker Hub." >&2
            exit 1
          fi

          # Strip sha256: prefix for our Helm values (template prepends it)
          STAT_DIGEST=${STAT_DIGEST_FULL#sha256:}
          DEV_DIGEST=${DEV_DIGEST_FULL#sha256:}

          echo "Resolved statistics-api digest: ${STAT_DIGEST_FULL}"
          echo "Resolved device-registration-api digest: ${DEV_DIGEST_FULL}"

          # Expose outputs for later steps (PR body)
          echo "STAT_DIGEST=${STAT_DIGEST}" >> "$GITHUB_OUTPUT"
          echo "DEV_DIGEST=${DEV_DIGEST}" >> "$GITHUB_OUTPUT"
          echo "DOCKER_ORG=${USER}" >> "$GITHUB_OUTPUT"

          # Update values/tst.yaml using yq
          yq -i '.statisticsapi.image.repository = "'"${USER}/statistics-api"'"' infrastructure/helm/lbsite/values/tst.yaml
          yq -i '.statisticsapi.image.digest = "'"${STAT_DIGEST}"'"' infrastructure/helm/lbsite/values/tst.yaml
          yq -i 'del(.statisticsapi.image.tag)' infrastructure/helm/lbsite/values/tst.yaml

          yq -i '.deviceregapi.image.repository = "'"${USER}/device-registration-api"'"' infrastructure/helm/lbsite/values/tst.yaml
          yq -i '.deviceregapi.image.digest = "'"${DEV_DIGEST}"'"' infrastructure/helm/lbsite/values/tst.yaml
          yq -i 'del(.deviceregapi.image.tag)' infrastructure/helm/lbsite/values/tst.yaml

      - name: Detect changes
        id: diff
        run: |
          git add infrastructure/helm/lbsite/values/tst.yaml
          if git diff --cached --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request for TST values update
        uses: peter-evans/create-pull-request@v6
        if: steps.diff.outputs.changed == 'true'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "ci(helm): promote TST values to digests for sha:${{ github.event.workflow_run.head_sha }}"
          title: "Promote TST to digests for sha:${{ github.event.workflow_run.head_sha }}"
          body: |
            This PR updates TST Helm values to deploy images (pinned by digest) built from CI commit `${{ github.event.workflow_run.head_sha }}`:
            - statisticsapi: `${{ steps.update-values.outputs.DOCKER_ORG }}/statistics-api@sha256:${{ steps.update-values.outputs.STAT_DIGEST }}`
            - deviceregapi: `${{ steps.update-values.outputs.DOCKER_ORG }}/device-registration-api@sha256:${{ steps.update-values.outputs.DEV_DIGEST }}`
          branch: ci/promote-tst-${{ github.event.workflow_run.head_sha }}
          base: main
          add-paths: |
            infrastructure/helm/lbsite/values/tst.yaml
          labels: |
            ci
            promote-tst
