# Default umbrella values (can be overridden by values/tst.yaml or values/prd.yaml)
statisticsapi:
  replicaCount: 1
  image:
    repository: balese/statistics-api
    tag: fix-manifest-2025-09-22
    pullPolicy: Always
  service:
    port: 8082
    targetPort: 8082
  env: {}

deviceregapi:
  replicaCount: 1
  image:
    repository: balese/device-registration-api
    tag: fix-manifest-2025-09-22
    pullPolicy: Always
  service:
    port: 8081
    targetPort: 8081
  env: {}
