# Default umbrella values (can be overridden by values/tst.yaml or values/prd.yaml)
statisticsapi:
  replicaCount: 1
  image:
    repository: DOCKER_HUB_USERNAME/statistics-api
    tag: latest
    pullPolicy: IfNotPresent
  service:
    port: 8082
    targetPort: 8082
  env: {}

deviceregapi:
  replicaCount: 1
  image:
    repository: DOCKER_HUB_USERNAME/device-registration-api
    tag: latest
    pullPolicy: IfNotPresent
  service:
    port: 8081
    targetPort: 8081
  env: {}
